services:
  app:
    container_name: nauticalcraft-bot
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: ../.env
    volumes:
      - ../src/:/app/src/
    ports:
      - '3000:3000'
    networks:
      - nauticalcraft-network
networks:
  nauticalcraft-network:
    driver: bridge