services:
  dev-postgresql:
    container_name: aletheia-postgresql
    image: postgres:latest
    env_file: ../../.env
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: ${DOCKER_DB_USER}
        POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
        POSTGRES_DB: ${DOCKER_DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - aletheia-network
    restart: always
networks:
  aletheia-network:
    driver: bridge